export const ROOM_MAX_CLIENTS = 20;
export const ROOM_ALLOW_RECONNECTION_TIMEOUT_SECONDS = 60;

export const REVEALING_STEP_DURATION_SECONDS = 5;
export const GUESSING_STEP_DURATION_SECONDS = 30;
export const SCORING_STEP_DURATION_SECONDS = 10;
